config/routes.rb
Rails.application.routes.draw do

  get 'default/index'
  resources :customers do
    resources :contracts
  end

  root 'default#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :customer

  after_initialize :set_default_start_time, :if => :new_record?
end

private

def set_default_start_time
  self.dateStart = Time.now
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :contracts, dependent: :destroy

  validates :firstName, presence: true, length: {minimum: 3}
  validates :name, presence: true, length: {minimum: 3}
  validates :salary, presence: true, length: {minimum: 1}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def create
    @customer = Customer.find(params[:customer_id])
    @contract = @customer.contracts.create(contract_params)
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @contract = @customer.contracts.find(params[:id])
    @contract.destroy
    redirect_to customer_path(@customer)
  end

  private
  def contract_params
    params.require(:contract).permit(:name, :description, :dateEnd)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'edit'
    end

  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy;

    redirect_to customers_path
  end
end

private

def customer_params
  params.require(:customer).permit(:firstName, :name, :salary)
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/views/contracts/_contract.html.erb
<div class="card-body border pb-1">
  <p>
    <strong>Name:</strong>
    <%= contract.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= contract.description %>
  </p>
  <p>
    <strong>Start Date:</strong>
    <%= contract.dateStart %>
  </p>
  <p>
    <strong>Due Date:</strong>
    <%= contract.dateEnd %>
  </p>
  <p>
    <%= link_to 'Destroy Contract', [contract.customer, contract], method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
  </p>
</div>

app/views/contracts/_form.html.erb
<%= form_with(model: [@customer, @customer.contracts.build], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :dateEnd, "Due Date" %><br>
    <%= form.datetime_field :dateEnd, :class => 'form-control' %>
  </div>
    <%= form.submit :class => 'btn btn-primary' %>
<% end %>

app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>

  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :firstName, "First Name" %><br>
    <%= form.text_field :firstName, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :salary %><br>
    <%= form.text_field :salary, :class => 'form-control' %>
  </div>

    <%= form.submit :class => 'btn btn-primary' %>

<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form' %>

<%= link_to 'Back to all', customers_path, :class => 'btn btn-secondary' %>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<table class="table">
  <tr>
    <th>First Name</th>
    <th>Name</th>
    <th>Salary</th>
    <th></th>
  </tr>

  <%= link_to 'New Customer', new_customer_path, :class => 'btn btn-primary mb-3 mt-1' %>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.firstName %></td>
      <td><%= customer.name %></td>
      <td><%= customer.salary %></td>
      <td class="d-flex justify-content-end">
        <div class="btn-group"><%= link_to 'Show', customer_path(customer), :class => 'btn btn-secondary' %>
          <%= link_to 'Edit', edit_customer_path(customer), :class => 'btn btn-primary' %>
          <%= link_to 'Destroy', customer_path(customer),
                      method: :delete,
                      data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back to all', customers_path, :class => 'btn btn-secondary'%>

app/views/customers/show.html.erb
<h1 class="display-4">Customer</h1>

<p>
  <strong>First Name:</strong>
  <%= @customer.firstName %>
</p>
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>
<p>
  <strong>Salary:</strong>
  <%= @customer.salary %>
</p>

<h2 class="mt-3">Contracts</h2>
<%= render @customer.contracts %>

<div class="border card-body mt-3 mb-2">
  <h2>Add a Contract:</h2>
  <%= render 'contracts/form' %>
</div>

<div class="btn-group">
  <%= link_to 'Back to all', customers_path, :class => 'btn btn-secondary' %>
  <%= link_to 'Edit', edit_customer_path, :class => 'btn btn-primary' %>
</div>

app/views/default/index.html.erb
<div class="text-center">
  <h1 class="display-1 text-center">Übung 3</h1>

  <h1 class="mt-5">
    <%= link_to 'Go to Customers (Model I)', customers_path %>
  </h1>

  <div class="mt-5">
    Made by <strong>Max Ripper</strong>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uebung3</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <%= yield %>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>